server:
  port: 8081
spring:
  application:
    name: asae-maestria-computacion
  datasource:
    # El nombre de la base de datos es "maestria-computacion", crear la base de datos vacia utf8_bin
    url: jdbc:mysql://localhost/jpa?useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect 
    properties:
      hibernate:  
        dialect: org.hibernate.dialect.MySQL8Dialect
      #javax:
        #persistence:
          #validation:
            #mode: none
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type: trace
